##first after terminl prefrence
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=jounraldb
#spring.data.mongodb.auto-index-creation=true
##spring.data.mongodb.uri= mongodb+srv://ysaini9466_db_user:yashsaini10@cluster0.rkstdwn.mongodb.net/taskmanagerdb
#
